### ISSUE TITLE
Exception: Failed to reset robot without collision

### ISSUE THREAD

**Issue by chaundm** [StanfordVL/GibsonEnvV2#17] opened 2019-12-23 08:25 UTC
Hi Fei XIa,

I have a trouble with running demo.py file. Most of things are work very well except for num_indices = 36. See my log file as followings: 
Could you please help to have a look at my problem?

using asset: path /home/cndm/Documents/GibsonEnvV2/gibson2/assets dataset path: /home/cndm/Documents/GibsonEnvV2/gibson2/assets/dataset
device 0 is available for rendering
device 1 is not available for rendering
device 2 is not available for rendering
device 3 is not available for rendering
using device 0
fisheye False
building scene: Ohoopee
floors [-2.3225653171539307, 0.03626394644379616, 2.945486545562744]
attrib.vertices =  699732
attrib.normals =  699732
attrib.texcoords =  625656
Num materials:  1
material_0
[1.0, 1.0, 1.0]
Num shapes:  1
{0: Material(type: texture, texture_id: 6, color: [0.5, 0.5, 0.5])}
(233244, 3) (233244, 3) (312828, 2)

material_id = 0
num_indices = 1373199
mesh_materials [0]
turtlebot/turtlebot.urdf
/home/cndm/Documents/GibsonEnvV2/gibson2/assets/models/turtlebot/kobuki_description/meshes/main_body.obj (0.0010000000474974513, 0.0, 0.051989998668432236) (0.0, 0.0, 0.0, 1.0) (1.0, 1.0, 1.0, 1.0) (1.0, 1.0, 1.0)
attrib.vertices =  12666
attrib.normals =  12666
attrib.texcoords =  9128
Num materials:  1
material_0
[1.0, 1.0, 1.0]
Num shapes:  1
{0: Material(type: texture, texture_id: 6, color: [0.5, 0.5, 0.5]), 1: Material(type: texture, texture_id: 7, color: [0.5, 0.5, 0.5]), 2: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0))}
(4222, 3) (4222, 3) (4564, 2)

material_id = 0
num_indices = 25320
mesh_materials [0, 1]
/home/cndm/Documents/GibsonEnvV2/gibson2/assets/models/mjcf_primitives/cube.obj (0.02, 0.01, 0.0) (0.0010000000474974513, 0.0, 0.051989998668432236) (0.0, 0.0, 0.0, 1.0) (1.0, 1.0, 1.0, 1.0)
attrib.vertices =  24
attrib.normals =  18
attrib.texcoords =  8
Num materials:  0
Num shapes:  1
{0: Material(type: texture, texture_id: 6, color: [0.5, 0.5, 0.5]), 1: Material(type: texture, texture_id: 7, color: [0.5, 0.5, 0.5]), 2: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 3: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0))}
(8, 3) (6, 3) (4, 2)
cube
material_id = -1
num_indices = 36
mesh_materials [0, 1, 3]
/home/cndm/Documents/GibsonEnvV2/gibson2/assets/models/turtlebot/kobuki_description/meshes/wheel.obj (0.0, 0.0, 0.0) (0.0, 0.0, 0.0, 1.0) (1.0, 1.0, 1.0, 1.0) (1.0, 1.0, 1.0)
attrib.vertices =  7188
attrib.normals =  7188
attrib.texcoords =  5376
Num materials:  1
material_0
[1.0, 1.0, 1.0]
Num shapes:  1
{0: Material(type: texture, texture_id: 6, color: [0.5, 0.5, 0.5]), 1: Material(type: texture, texture_id: 7, color: [0.5, 0.5, 0.5]), 2: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 3: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 4: Material(type: texture, texture_id: 8, color: [0.5, 0.5, 0.5]), 5: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0))}
(2396, 3) (2396, 3) (2688, 2)

material_id = 0
num_indices = 14364
mesh_materials [0, 1, 3, 4]
/home/cndm/Documents/GibsonEnvV2/gibson2/assets/models/mjcf_primitives/cube.obj (0.0176, 0.017, 0.0) (0.0, 0.0, 0.0) (0.0, 0.0, 0.0, 1.0) (0.28125, 0.51953125, 0.92578125, 1.0)
attrib.vertices =  24
attrib.normals =  18
attrib.texcoords =  8
Num materials:  0
Num shapes:  1
{0: Material(type: texture, texture_id: 6, color: [0.5, 0.5, 0.5]), 1: Material(type: texture, texture_id: 7, color: [0.5, 0.5, 0.5]), 2: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 3: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 4: Material(type: texture, texture_id: 8, color: [0.5, 0.5, 0.5]), 5: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 6: Material(type: color, texture_id: None, color: (0.28125, 0.51953125, 0.92578125))}
(8, 3) (6, 3) (4, 2)
cube
material_id = -1
num_indices = 36
mesh_materials [0, 1, 3, 4, 6]
/home/cndm/Documents/GibsonEnvV2/gibson2/assets/models/mjcf_primitives/cube.obj (0.0176, 0.017, 0.0) (0.0, 0.0, 0.0) (0.0, 0.0, 0.0, 1.0) (0.234375, 0.7265625, 0.328125, 1.0)
attrib.vertices =  24
attrib.normals =  18
attrib.texcoords =  8
Num materials:  0
Num shapes:  1
{0: Material(type: texture, texture_id: 6, color: [0.5, 0.5, 0.5]), 1: Material(type: texture, texture_id: 7, color: [0.5, 0.5, 0.5]), 2: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 3: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 4: Material(type: texture, texture_id: 8, color: [0.5, 0.5, 0.5]), 5: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 6: Material(type: color, texture_id: None, color: (0.28125, 0.51953125, 0.92578125)), 7: Material(type: color, texture_id: None, color: (0.234375, 0.7265625, 0.328125))}
(8, 3) (6, 3) (4, 2)
cube
material_id = -1
num_indices = 36
mesh_materials [0, 1, 3, 4, 6, 7]
/home/cndm/Documents/GibsonEnvV2/gibson2/assets/models/turtlebot/turtlebot_description/meshes/stacks/hexagons/pole_bottom.obj (0.0, 0.0, 0.0) (0.0, 0.0, 0.0, 1.0) (1.0, 1.0, 1.0, 1.0) (1.0, 1.0, 1.0)
attrib.vertices =  684
attrib.normals =  684
attrib.texcoords =  932
Num materials:  1
material_0
[1.0, 1.0, 1.0]
Num shapes:  1
{0: Material(type: texture, texture_id: 6, color: [0.5, 0.5, 0.5]), 1: Material(type: texture, texture_id: 7, color: [0.5, 0.5, 0.5]), 2: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 3: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 4: Material(type: texture, texture_id: 8, color: [0.5, 0.5, 0.5]), 5: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 6: Material(type: color, texture_id: None, color: (0.28125, 0.51953125, 0.92578125)), 7: Material(type: color, texture_id: None, color: (0.234375, 0.7265625, 0.328125)), 8: Material(type: texture, texture_id: 9, color: [0.5, 0.5, 0.5]), 9: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0))}
(228, 3) (228, 3) (466, 2)

material_id = 0
num_indices = 1356
mesh_materials [0, 1, 3, 4, 6, 7, 8]
/home/cndm/Documents/GibsonEnvV2/gibson2/assets/models/turtlebot/turtlebot_description/meshes/stacks/hexagons/plate_bottom.obj (0.0, 0.0, 0.0) (0.0, 0.0, 0.0, 1.0) (1.0, 1.0, 1.0, 1.0) (1.0, 1.0, 1.0)
attrib.vertices =  672
attrib.normals =  672
attrib.texcoords =  924
Num materials:  1
material_0
[1.0, 1.0, 1.0]
Num shapes:  1
{0: Material(type: texture, texture_id: 6, color: [0.5, 0.5, 0.5]), 1: Material(type: texture, texture_id: 7, color: [0.5, 0.5, 0.5]), 2: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 3: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 4: Material(type: texture, texture_id: 8, color: [0.5, 0.5, 0.5]), 5: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 6: Material(type: color, texture_id: None, color: (0.28125, 0.51953125, 0.92578125)), 7: Material(type: color, texture_id: None, color: (0.234375, 0.7265625, 0.328125)), 8: Material(type: texture, texture_id: 9, color: [0.5, 0.5, 0.5]), 9: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 10: Material(type: texture, texture_id: 10, color: [0.5, 0.5, 0.5]), 11: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0))}
(224, 3) (224, 3) (462, 2)

material_id = 0
num_indices = 1332
mesh_materials [0, 1, 3, 4, 6, 7, 8, 10]
/home/cndm/Documents/GibsonEnvV2/gibson2/assets/models/turtlebot/turtlebot_description/meshes/stacks/hexagons/pole_middle.obj (0.0, 0.0, 0.0) (0.0, 0.999999999999999, 0.0, -4.371139000186241e-08) (1.0, 1.0, 1.0, 1.0) (1.0, 1.0, 1.0)
attrib.vertices =  816
attrib.normals =  816
attrib.texcoords =  1108
Num materials:  1
material_0
[1.0, 1.0, 1.0]
Num shapes:  1
{0: Material(type: texture, texture_id: 6, color: [0.5, 0.5, 0.5]), 1: Material(type: texture, texture_id: 7, color: [0.5, 0.5, 0.5]), 2: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 3: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 4: Material(type: texture, texture_id: 8, color: [0.5, 0.5, 0.5]), 5: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 6: Material(type: color, texture_id: None, color: (0.28125, 0.51953125, 0.92578125)), 7: Material(type: color, texture_id: None, color: (0.234375, 0.7265625, 0.328125)), 8: Material(type: texture, texture_id: 9, color: [0.5, 0.5, 0.5]), 9: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 10: Material(type: texture, texture_id: 10, color: [0.5, 0.5, 0.5]), 11: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 12: Material(type: texture, texture_id: 11, color: [0.5, 0.5, 0.5]), 13: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0))}
(272, 3) (272, 3) (554, 2)

material_id = 0
num_indices = 1620
mesh_materials [0, 1, 3, 4, 6, 7, 8, 10, 12]
/home/cndm/Documents/GibsonEnvV2/gibson2/assets/models/turtlebot/turtlebot_description/meshes/stacks/hexagons/plate_middle.obj (0.0, 0.0, 0.0) (0.0, 0.0, 0.0, 1.0) (1.0, 1.0, 1.0, 1.0) (1.0, 1.0, 1.0)
attrib.vertices =  1548
attrib.normals =  1548
attrib.texcoords =  2112
Num materials:  1
material_0
[1.0, 1.0, 1.0]
Num shapes:  1
{0: Material(type: texture, texture_id: 6, color: [0.5, 0.5, 0.5]), 1: Material(type: texture, texture_id: 7, color: [0.5, 0.5, 0.5]), 2: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 3: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 4: Material(type: texture, texture_id: 8, color: [0.5, 0.5, 0.5]), 5: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 6: Material(type: color, texture_id: None, color: (0.28125, 0.51953125, 0.92578125)), 7: Material(type: color, texture_id: None, color: (0.234375, 0.7265625, 0.328125)), 8: Material(type: texture, texture_id: 9, color: [0.5, 0.5, 0.5]), 9: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 10: Material(type: texture, texture_id: 10, color: [0.5, 0.5, 0.5]), 11: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 12: Material(type: texture, texture_id: 11, color: [0.5, 0.5, 0.5]), 13: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 14: Material(type: texture, texture_id: 12, color: [0.5, 0.5, 0.5]), 15: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0))}
(516, 3) (516, 3) (1056, 2)

material_id = 0
num_indices = 3084
mesh_materials [0, 1, 3, 4, 6, 7, 8, 10, 12, 14]
/home/cndm/Documents/GibsonEnvV2/gibson2/assets/models/turtlebot/turtlebot_description/meshes/stacks/hexagons/pole_top.obj (0.0, 0.0, 0.0) (0.0, 0.0, 0.0, 1.0) (1.0, 1.0, 1.0, 1.0) (1.0, 1.0, 1.0)
attrib.vertices =  324
attrib.normals =  324
attrib.texcoords =  448
Num materials:  1
material_0
[1.0, 1.0, 1.0]
Num shapes:  1
{0: Material(type: texture, texture_id: 6, color: [0.5, 0.5, 0.5]), 1: Material(type: texture, texture_id: 7, color: [0.5, 0.5, 0.5]), 2: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 3: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 4: Material(type: texture, texture_id: 8, color: [0.5, 0.5, 0.5]), 5: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 6: Material(type: color, texture_id: None, color: (0.28125, 0.51953125, 0.92578125)), 7: Material(type: color, texture_id: None, color: (0.234375, 0.7265625, 0.328125)), 8: Material(type: texture, texture_id: 9, color: [0.5, 0.5, 0.5]), 9: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 10: Material(type: texture, texture_id: 10, color: [0.5, 0.5, 0.5]), 11: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 12: Material(type: texture, texture_id: 11, color: [0.5, 0.5, 0.5]), 13: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 14: Material(type: texture, texture_id: 12, color: [0.5, 0.5, 0.5]), 15: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 16: Material(type: texture, texture_id: 13, color: [0.5, 0.5, 0.5]), 17: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0))}
(108, 3) (108, 3) (224, 2)

material_id = 0
num_indices = 636
mesh_materials [0, 1, 3, 4, 6, 7, 8, 10, 12, 14, 16]
/home/cndm/Documents/GibsonEnvV2/gibson2/assets/models/turtlebot/turtlebot_description/meshes/stacks/hexagons/pole_kinect.obj (0.0, 0.0, 0.0) (0.0, 0.0, 0.0, 1.0) (1.0, 1.0, 1.0, 1.0) (1.0, 1.0, 1.0)
attrib.vertices =  1020
attrib.normals =  1020
attrib.texcoords =  1224
Num materials:  1
material_0
[1.0, 1.0, 1.0]
Num shapes:  1
{0: Material(type: texture, texture_id: 6, color: [0.5, 0.5, 0.5]), 1: Material(type: texture, texture_id: 7, color: [0.5, 0.5, 0.5]), 2: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 3: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 4: Material(type: texture, texture_id: 8, color: [0.5, 0.5, 0.5]), 5: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 6: Material(type: color, texture_id: None, color: (0.28125, 0.51953125, 0.92578125)), 7: Material(type: color, texture_id: None, color: (0.234375, 0.7265625, 0.328125)), 8: Material(type: texture, texture_id: 9, color: [0.5, 0.5, 0.5]), 9: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 10: Material(type: texture, texture_id: 10, color: [0.5, 0.5, 0.5]), 11: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 12: Material(type: texture, texture_id: 11, color: [0.5, 0.5, 0.5]), 13: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 14: Material(type: texture, texture_id: 12, color: [0.5, 0.5, 0.5]), 15: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 16: Material(type: texture, texture_id: 13, color: [0.5, 0.5, 0.5]), 17: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 18: Material(type: texture, texture_id: 14, color: [0.5, 0.5, 0.5]), 19: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0))}
(340, 3) (340, 3) (612, 2)

material_id = 0
num_indices = 2028
mesh_materials [0, 1, 3, 4, 6, 7, 8, 10, 12, 14, 16, 18]
/home/cndm/Documents/GibsonEnvV2/gibson2/assets/models/turtlebot/turtlebot_description/meshes/stacks/hexagons/plate_top.obj (0.0, 0.0, 0.0) (0.0, 0.0, 0.0, 1.0) (1.0, 1.0, 1.0, 1.0) (1.0, 1.0, 1.0)
attrib.vertices =  1548
attrib.normals =  1548
attrib.texcoords =  2112
Num materials:  1
material_0
[1.0, 1.0, 1.0]
Num shapes:  1
{0: Material(type: texture, texture_id: 6, color: [0.5, 0.5, 0.5]), 1: Material(type: texture, texture_id: 7, color: [0.5, 0.5, 0.5]), 2: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 3: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 4: Material(type: texture, texture_id: 8, color: [0.5, 0.5, 0.5]), 5: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 6: Material(type: color, texture_id: None, color: (0.28125, 0.51953125, 0.92578125)), 7: Material(type: color, texture_id: None, color: (0.234375, 0.7265625, 0.328125)), 8: Material(type: texture, texture_id: 9, color: [0.5, 0.5, 0.5]), 9: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 10: Material(type: texture, texture_id: 10, color: [0.5, 0.5, 0.5]), 11: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 12: Material(type: texture, texture_id: 11, color: [0.5, 0.5, 0.5]), 13: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 14: Material(type: texture, texture_id: 12, color: [0.5, 0.5, 0.5]), 15: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 16: Material(type: texture, texture_id: 13, color: [0.5, 0.5, 0.5]), 17: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 18: Material(type: texture, texture_id: 14, color: [0.5, 0.5, 0.5]), 19: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 20: Material(type: texture, texture_id: 15, color: [0.5, 0.5, 0.5]), 21: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0))}
(516, 3) (516, 3) (1056, 2)

material_id = 0
num_indices = 3084
mesh_materials [0, 1, 3, 4, 6, 7, 8, 10, 12, 14, 16, 18, 20]
/home/cndm/Documents/GibsonEnvV2/gibson2/assets/models/turtlebot/turtlebot_description/meshes/sensors/kinect.obj (0.0, 0.0, 0.0) (0.0, 0.0, 0.7071067966408575, 0.7071067657322372) (1.0, 1.0, 1.0, 1.0) (1.0, 1.0, 1.0)
attrib.vertices =  9639
attrib.normals =  9639
attrib.texcoords =  7588
Num materials:  1
material_0
[1.0, 1.0, 1.0]
Num shapes:  1
{0: Material(type: texture, texture_id: 6, color: [0.5, 0.5, 0.5]), 1: Material(type: texture, texture_id: 7, color: [0.5, 0.5, 0.5]), 2: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 3: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 4: Material(type: texture, texture_id: 8, color: [0.5, 0.5, 0.5]), 5: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 6: Material(type: color, texture_id: None, color: (0.28125, 0.51953125, 0.92578125)), 7: Material(type: color, texture_id: None, color: (0.234375, 0.7265625, 0.328125)), 8: Material(type: texture, texture_id: 9, color: [0.5, 0.5, 0.5]), 9: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 10: Material(type: texture, texture_id: 10, color: [0.5, 0.5, 0.5]), 11: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 12: Material(type: texture, texture_id: 11, color: [0.5, 0.5, 0.5]), 13: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 14: Material(type: texture, texture_id: 12, color: [0.5, 0.5, 0.5]), 15: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 16: Material(type: texture, texture_id: 13, color: [0.5, 0.5, 0.5]), 17: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 18: Material(type: texture, texture_id: 14, color: [0.5, 0.5, 0.5]), 19: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 20: Material(type: texture, texture_id: 15, color: [0.5, 0.5, 0.5]), 21: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 22: Material(type: texture, texture_id: 16, color: [0.5, 0.5, 0.5]), 23: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0))}
(3213, 3) (3213, 3) (3794, 2)

material_id = 0
num_indices = 19254
mesh_materials [0, 1, 3, 4, 6, 7, 8, 10, 12, 14, 16, 18, 20, 22]
attrib.vertices =  24
attrib.normals =  18
attrib.texcoords =  8
Num materials:  0
Num shapes:  1
{0: Material(type: texture, texture_id: 6, color: [0.5, 0.5, 0.5]), 1: Material(type: texture, texture_id: 7, color: [0.5, 0.5, 0.5]), 2: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 3: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 4: Material(type: texture, texture_id: 8, color: [0.5, 0.5, 0.5]), 5: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 6: Material(type: color, texture_id: None, color: (0.28125, 0.51953125, 0.92578125)), 7: Material(type: color, texture_id: None, color: (0.234375, 0.7265625, 0.328125)), 8: Material(type: texture, texture_id: 9, color: [0.5, 0.5, 0.5]), 9: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 10: Material(type: texture, texture_id: 10, color: [0.5, 0.5, 0.5]), 11: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 12: Material(type: texture, texture_id: 11, color: [0.5, 0.5, 0.5]), 13: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 14: Material(type: texture, texture_id: 12, color: [0.5, 0.5, 0.5]), 15: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 16: Material(type: texture, texture_id: 13, color: [0.5, 0.5, 0.5]), 17: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 18: Material(type: texture, texture_id: 14, color: [0.5, 0.5, 0.5]), 19: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 20: Material(type: texture, texture_id: 15, color: [0.5, 0.5, 0.5]), 21: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 22: Material(type: texture, texture_id: 16, color: [0.5, 0.5, 0.5]), 23: Material(type: color, texture_id: None, color: (1.0, 1.0, 1.0)), 24: Material(type: color, texture_id: None, color: (0.0, 0.0, 1.0))}
(8, 3) (6, 3) (4, 2)
cube
material_id = -1
num_indices = 36
mesh_materials [0, 1, 3, 4, 6, 7, 8, 10, 12, 14, 16, 18, 20, 22, 24]
pybullet build time: Dec 17 2019 12:16:21
startThreads creating 1 threads.
starting thread 0
started thread 0 
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsym OK!
X11 functions dynamically loaded using dlopen/dlsym OK!
Creating context
Created GL 3.3 context
Direct GLX rendering context obtained
Making context current
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=GeForce RTX 2070/PCIe/SSE2
GL_VERSION=3.3.0 NVIDIA 440.44
GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
pthread_getconcurrency()=0
Version = 3.3.0 NVIDIA 440.44
Vendor = NVIDIA Corporation
Renderer = GeForce RTX 2070/PCIe/SSE2
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0 
MotionThreadFunc thread started
ven = NVIDIA Corporation
Traceback (most recent call last):
  File "examples/demo/demo.py", line 13, in <module>
    nav_env.reset()
  File "/home/cndm/Documents/GibsonEnvV2/gibson2/envs/locomotor_env.py", line 587, in reset
    state = super(NavigateRandomEnv, self).reset()
  File "/home/cndm/Documents/GibsonEnvV2/gibson2/envs/locomotor_env.py", line 519, in reset
    self.reset_agent()
  File "/home/cndm/Documents/GibsonEnvV2/gibson2/envs/locomotor_env.py", line 502, in reset_agent
    raise Exception("Failed to reset robot without collision")
Exception: Failed to reset robot without collision
numActiveThreads = 0
stopping threads
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed
finished
numActiveThreads = 0
btShutDownExampleBrowser stopping threads
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed

**Comment by shantanusingh16** [comment] 2019-12-26 04:39
A fix for the same has been merged a few hours ago. Can you pull the latest code and try again?

**Comment by fxia22** [comment] 2019-12-26 06:17
It is caused by floor height being too high so every initialization ends up in collision. Please try the latest commit from master branch. Also, increasing `random_init_z_offset` in yaml file (to >0.15) can also solve the issue.

**Closed** 2019-12-27 08:17 UTC
